"""Hard-negative generation (paper Section 2.3 + 2.6).

Strategy:
- Confusable input, different correct output. Generated by teacher LLM in batches.
- 2-for-1 rule: each gold gets one paired hard-negative sharing a `pair_key`.
- For NER: replace entity with confusable surface form different in type/span.
- For classification: nearest-neighbor in embedding space with different label.
"""
from __future__ import annotations
import json
import random
from typing import Optional

from ..llm import LLMClient
from .curate import Example


HARDNEG_SYSTEM = """You generate hard-negative training examples.
Given a gold (input, output, label?), produce ONE confusable example: an input that
looks similar but the correct output is DIFFERENT. Aim to teach the model when
NOT to fire the original answer.

Output strict JSON: {"input": str, "output": str, "label": str|null, "rationale": str}.
"""


def generate_hard_negatives(
    client: LLMClient,
    golds: list[Example],
    max_neg_per_gold: int = 1,
    batch_size: int = 8,
) -> list[Example]:
    out: list[Example] = []
    rng = random.Random(42)
    for i, gold in enumerate(golds):
        for _ in range(max_neg_per_gold):
            payload = {
                "gold": {"input": gold.input, "output": gold.output, "label": gold.label},
                "instruction": "Confusable input, different correct output. JSON only.",
            }
            try:
                resp = client.complete(
                    [{"role": "user", "content": json.dumps(payload, default=str)}],
                    system=HARDNEG_SYSTEM,
                )
                text = resp.content.strip()
                if "```" in text:
                    text = text.split("```", 1)[-1].split("```", 1)[0]
                    if text.startswith("json"):
                        text = text[4:]
                data = json.loads(text)
                pair_key = f"pair_{i}_{rng.randint(0, 1<<30)}"
                gold.metadata.setdefault("pair_key", pair_key)
                out.append(Example(
                    input=str(data["input"]),
                    output=str(data["output"]),
                    label=data.get("label"),
                    is_hard_negative=True,
                    metadata={"pair_key": pair_key, "rationale": data.get("rationale", "")[:300]},
                ))
            except Exception:
                continue
    return out


def nn_label_swap_hard_negatives(
    examples: list[Example], k: int = 1
) -> list[Example]:
    """Cheap fallback: nearest-neighbor in TF-IDF, take inputs whose label differs."""
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    if len(examples) < 4:
        return []
    texts = [ex.input for ex in examples]
    labels = [ex.label for ex in examples]
    v = TfidfVectorizer(min_df=1).fit_transform(texts)
    sims = cosine_similarity(v)
    out: list[Example] = []
    for i, ex in enumerate(examples):
        order = sims[i].argsort()[::-1]
        added = 0
        for j in order:
            if i == j:
                continue
            if labels[j] != labels[i] and labels[j] is not None:
                pair_key = f"nnpair_{i}_{j}"
                ex.metadata.setdefault("pair_key", pair_key)
                neg = Example(
                    input=examples[j].input, output=ex.output, label=labels[i],
                    is_hard_negative=True, metadata={"pair_key": pair_key},
                )
                out.append(neg)
                added += 1
                if added >= k:
                    break
    return out
